# Generated by Django 5.2.11 on 2026-02-12 11:12

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AddressEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line1', models.CharField(max_length=255)),
                ('line2', models.CharField(blank=True, max_length=255, null=True)),
                ('town', models.CharField(max_length=100)),
                ('postcode', models.CharField(max_length=10)),
                ('move_in_date', models.DateField()),
                ('is_current', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address_history', to='applications.application')),
            ],
            options={
                'ordering': ['-move_in_date'],
            },
        ),
        migrations.CreateModel(
            name='PersonalDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_names', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('gender', models.CharField(max_length=20)),
                ('known_by_other_names', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('ni_number', models.CharField(max_length=9, validators=[django.core.validators.RegexValidator('^[A-CEGHJ-PR-TW-Z]{1}[A-CEGHJ-NPR-TW-Z]{1}[0-9]{6}[A-D]{1}$', 'Invalid NI number format')], verbose_name='National Insurance Number')),
                ('right_to_work_status', models.CharField(max_length=100)),
                ('lived_outside_uk', models.BooleanField(default=False)),
                ('military_base_abroad', models.BooleanField(default=False)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personal_details', to='applications.application')),
            ],
        ),
        migrations.CreateModel(
            name='Premises',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_authority', models.CharField(max_length=100)),
                ('premises_type', models.CharField(choices=[('Domestic', 'Domestic (Home)'), ('Non-domestic', 'Non-domestic')], max_length=20)),
                ('is_own_home', models.BooleanField(default=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='premises', to='applications.application')),
            ],
        ),
    ]
