# Generated by Django 5.2.11 on 2026-02-12 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='premises',
            name='has_outdoor_space',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='premises',
            name='has_pets',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='premises',
            name='pets_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ChildcareService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('care_age_0_5', models.BooleanField(default=False, verbose_name='0-5 years')),
                ('care_age_5_8', models.BooleanField(default=False, verbose_name='5-7 years')),
                ('care_age_8_plus', models.BooleanField(default=False, verbose_name='8+ years')),
                ('work_with_assistants', models.BooleanField(default=False)),
                ('number_of_assistants', models.IntegerField(default=0)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='service_details', to='applications.application')),
            ],
        ),
        migrations.CreateModel(
            name='Declaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consent_auth_contact', models.BooleanField(default=False)),
                ('consent_auth_share', models.BooleanField(default=False)),
                ('consent_understand_usage', models.BooleanField(default=False)),
                ('consent_understand_gdpr', models.BooleanField(default=False)),
                ('consent_truth', models.BooleanField(default=False)),
                ('signature', models.CharField(max_length=255)),
                ('print_name', models.CharField(max_length=255)),
                ('date_signed', models.DateField()),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='declaration', to='applications.application')),
            ],
        ),
        migrations.CreateModel(
            name='EmploymentEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employer_name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employment_history', to='applications.application')),
            ],
        ),
        migrations.CreateModel(
            name='HouseholdMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('relationship', models.CharField(max_length=100)),
                ('is_adult', models.BooleanField(default=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='household_members', to='applications.application')),
            ],
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('relationship', models.CharField(max_length=100)),
                ('years_known', models.IntegerField()),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='applications.application')),
            ],
        ),
        migrations.CreateModel(
            name='Suitability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_medical_condition', models.BooleanField(default=False)),
                ('medical_condition_details', models.TextField(blank=True, null=True)),
                ('is_disqualified', models.BooleanField(default=False)),
                ('social_services_involved', models.BooleanField(default=False)),
                ('social_services_details', models.TextField(blank=True, null=True)),
                ('has_dbs', models.BooleanField(default=False)),
                ('dbs_number', models.CharField(blank=True, max_length=12, null=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='suitability', to='applications.application')),
            ],
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_aid_completed', models.BooleanField(default=False)),
                ('first_aid_date', models.DateField(blank=True, null=True)),
                ('first_aid_org', models.CharField(blank=True, max_length=255, null=True)),
                ('safeguarding_completed', models.BooleanField(default=False)),
                ('safeguarding_date', models.DateField(blank=True, null=True)),
                ('safeguarding_org', models.CharField(blank=True, max_length=255, null=True)),
                ('eyfs_completed', models.BooleanField(default=False)),
                ('eyfs_date', models.DateField(blank=True, null=True)),
                ('eyfs_org', models.CharField(blank=True, max_length=255, null=True)),
                ('food_hygiene_completed', models.BooleanField(default=False)),
                ('food_hygiene_date', models.DateField(blank=True, null=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='training', to='applications.application')),
            ],
        ),
    ]
