# Generated by Django 5.2.11 on 2026-02-13 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_premises_has_outdoor_space_premises_has_pets_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldetails',
            name='right_to_work_status',
            field=models.CharField(choices=[('British Citizen', 'British Citizen'), ('Irish Citizen', 'Irish Citizen'), ('EU Settled Status', 'EU Settled Status'), ('EU Pre-settled Status', 'EU Pre-settled Status'), ('Visa / Work Permit', 'Visa / Work Permit')], max_length=100),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='title',
            field=models.CharField(choices=[('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Miss', 'Miss'), ('Ms', 'Ms'), ('Mx', 'Mx'), ('Dr', 'Dr'), ('Other', 'Other')], max_length=10),
        ),
    ]
