# Generated by Django 5.2.11 on 2026-02-13 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_alter_personaldetails_right_to_work_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reference',
            name='full_name',
        ),
        migrations.AddField(
            model_name='reference',
            name='first_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reference',
            name='last_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reference',
            name='years_known',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
