# Generated by Django 5.2.11 on 2026-02-16 12:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_remove_reference_full_name_reference_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='last_section_completed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='addressentry',
            name='line1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='addressentry',
            name='move_in_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='addressentry',
            name='postcode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='addressentry',
            name='town',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='declaration',
            name='date_signed',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='declaration',
            name='print_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='declaration',
            name='signature',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='employmententry',
            name='employer_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='employmententry',
            name='role',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='employmententry',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='householdmember',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='householdmember',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='householdmember',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='householdmember',
            name='relationship',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='dob',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='gender',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='ni_number',
            field=models.CharField(blank=True, max_length=9, null=True, validators=[django.core.validators.RegexValidator('^[A-Z]{2}[0-9]{6}[A-D]{1}$', 'Invalid NI number format')], verbose_name='National Insurance Number'),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='right_to_work_status',
            field=models.CharField(blank=True, choices=[('British Citizen', 'British Citizen'), ('Irish Citizen', 'Irish Citizen'), ('EU Settled Status', 'EU Settled Status'), ('EU Pre-settled Status', 'EU Pre-settled Status'), ('Visa / Work Permit', 'Visa / Work Permit')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='title',
            field=models.CharField(blank=True, choices=[('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Miss', 'Miss'), ('Ms', 'Ms'), ('Mx', 'Mx'), ('Dr', 'Dr'), ('Other', 'Other')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='premises',
            name='local_authority',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='premises',
            name='premises_type',
            field=models.CharField(blank=True, choices=[('Domestic', 'Domestic (Home)'), ('Non-domestic', 'Non-domestic')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='reference',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='reference',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='reference',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='reference',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='reference',
            name='relationship',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
