# Generated by Django 5.2.11 on 2026-02-16 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_application_last_section_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='eyfs_course_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='training',
            name='food_hygiene_org',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='training',
            name='level2_qual_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='training',
            name='level2_qual_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='training',
            name='level2_qual_org',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
