# Generated by Django 5.2.11 on 2026-02-16 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_training_eyfs_course_title_training_food_hygiene_org_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressentry',
            name='move_out_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='has_adults_in_home',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='has_children_in_home',
            field=models.BooleanField(default=False),
        ),
    ]
