# Generated by Django 5.2.11 on 2026-02-18 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0007_addressentry_move_out_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='application_number',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True),
        ),
    ]
